vich_uploader:
    db_driver: orm

    mappings:
       users_images:
           uri_prefix: /images/users
           upload_destination: '%kernel.project_dir%/public/images/users'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       items_images:
           uri_prefix: /images/items
           upload_destination: '%kernel.project_dir%/public/images/items'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

