controllers_front:
    resource: ../src/Controller/Front/
    type: attribute
    name_prefix: front_

controllers_back:
    resource: ../src/Controller/Back/
    type: attribute
    prefix: /admin/
    name_prefix: back_

not_found:
    path: /{wildcard}
    controller: App\Controller\Front\HomeController::redirectAction
    requirements:
      wildcard: ".+"
