---
- hosts: all
  become: yes
  vars:
      user_to_add: "admin"

  # Update and upgrade all packages
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes

  # Install docker
  tasks:
      - name: Install apt-transport-https
        ansible.builtin.apt:
          name:
            - apt-transport-https
            - ca-certificates
            - lsb-release
            - gnupg
          state: latest
          update_cache: true

      - name: Add signing key
        ansible.builtin.apt_key:
          url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
          state: present

      - name: Add repository into sources list
        ansible.builtin.apt_repository:
          repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
          state: present
          filename: docker

      - name: Install Docker
        ansible.builtin.apt:
          name:
            - docker
            - docker.io
            - docker-compose
            - docker-registry
          state: latest
          update_cache: true

      - name: Enable docker
        command: systemctl enable docker

      - name: Create docker group
        group: 
          name: "docker"
          state: present

      - name: Add user to docker group
        user: 
          name: "{{ user_to_add }}"
          groups: docker
          append: yes
